logo_title: Front-End

style: black

favicon: /favicon.ico

menu:
 # 域名: /domain
 # 友联: /links
  Play : /project
  Github: https://github.com/goodwjf
  About me: /about

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false
  appId: CmCti21ooOOIzFOhEyFkFvR0-gzGzoHsz
  appKey: FqiyUqbg7McKN2eG0MCewupf

highlight:
  enable: false